# Generated by Django 3.2.3 on 2021-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AseModel', '0009_auto_20210620_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanport',
            options={'verbose_name': 'port info', 'verbose_name_plural': 'port info'},
        ),
        migrations.AlterModelOptions(
            name='scanvuln',
            options={'verbose_name': 'vuln info', 'verbose_name_plural': 'vuln info'},
        ),
        migrations.AlterField(
            model_name='scanvuln',
            name='scan_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
